# Server configuration
server:
  port: 8080
  
# JPA configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elearning
    username: postgres
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
         