# Server configuration
server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/elearning
#    url: jdbc:postgresql://localhost:5432/elearning
    username: postgres
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false