server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elearning
    username: postgres
    password: admin
#    driver-class-name: com.postgresql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false         
     
         